[RC2] Restructuring chapter structure and adding reading guide
cntt-n/CNTT pull request #1926
Opened 2020-08-27 11:02 UTC by xmulligan

2020-08-27 17:03 UTC, tomkivlin requested changes

2020-08-27 17:03 UTC, tomkivlin commented on doc/ref_cert/RC2/chapters/chapter02.md
> +# 3. Kubernetes Test Cases and Traceability to CNTT Requirements
I think there is a drive to not use the term "CNTT" - suggestion below
```suggestion
# 3. Kubernetes Test Cases and Requirements Traceability
```

2020-08-27 17:03 UTC, tomkivlin commented on doc/ref_cert/RC2/README.md
> +| Chapter 02 - Kubernetes Test Cases and Traceability to CNTT Requirements  | Initial Framework Only |
I think there is a drive to not use the term "CNTT" - suggestion below

```suggestion
| Chapter 02 - Kubernetes Test Cases and Requirements Traceability | Initial Framework Only |
```

2020-08-27 17:03 UTC, tomkivlin commented on doc/ref_cert/RC2/README.md
> +| Chapter 04 - CNF Test Cases and Traceability to CNTT Requirements         | Initial Framework Only |
I think there is a drive to not use the term "CNTT" - suggestion below

```suggestion
| Chapter 04 - CNF Test Cases and Requirements Traceability | Initial Framework Only |
```

2020-08-27 17:03 UTC, tomkivlin commented on doc/ref_cert/RC2/README.md
> +* [Chapter 02 - Kubernetes Test Cases and Traceability to CNTT Requirements ](chapters/chapter02.md)
I think there is a drive to not use the term "CNTT" - suggestion below

```suggestion
* [Chapter 02 - Kubernetes Test Cases and Requirements Traceability](chapters/chapter02.md)
```

2020-08-27 17:03 UTC, tomkivlin commented on doc/ref_cert/RC2/README.md
> +* [Chapter 04 - CNF Test Cases and Traceability to CNTT Requirements](chapters/chapter04.md)
I think there is a drive to not use the term "CNTT" - suggestion below

```suggestion
* [Chapter 04 - CNF Test Cases and Requirements Traceability](chapters/chapter04.md)
```

2020-08-27 17:03 UTC, tomkivlin commented on doc/ref_cert/RC2/chapters/chapter04.md
> +# 4. CNF Test Cases and Traceability to CNTT Requirements
I think there is a drive to not use the term "CNTT" - suggestion below

```suggestion
# 4. CNF Test Cases and Requirements Traceability
```

2020-08-27 18:42 UTC, xmulligan commented
@tomkivlin thanks, I've accepted your changes to remove CNTT

2020-08-27 18:42 UTC, tomkivlin approved these changes

2020-09-11 21:27 UTC, scottsteinbrueck commented
@xmulligan @tomkivlin Can you work to resolve conflicts and prepare for PR merge ?  Thanks.

2020-09-13 16:21 UTC, collivier commented
Removing empty chapters should rather occur at the beginning not at the end of the development period.
The merge looks good but I do double check it.

It's mostly unreviewable due to the huge amount of commits. Only 1.6 is now right?

2020-09-13 16:23 UTC, collivier requested changes
Would you mind formating tabs?

2020-09-17 15:46 UTC, xmulligan commented
@scottsteinbrueck the conflicts have been removed
@collivier I formatted the tabs

Can you both check again?

2020-09-18 18:19 UTC, scottsteinbrueck commented
@collivier if you review / approve, then I will add my approve / merge.
@xmulligan FYI

2020-09-20 10:27 UTC, collivier commented
@scottsteinbrueck we shouldn't merge restructuring during proof reading. As @tomkivlin managed the most difficult part, let's check if it's safe enough

2020-09-20 10:41 UTC, collivier commented
It would be great to manage git in the appropriate way.
Pushing so many commits is good for stats but not for rebasing branches.

2020-09-20 11:01 UTC, collivier commented
@xmulligan your last proposal simply remove contents which are important. Am I allowed to fix all history here?

2020-09-20 11:44 UTC, collivier approved these changes
Let's merge it as it seems now clean

2020-09-20 11:45 UTC, merged

2020-09-21 10:13 UTC, xmulligan commented
@collivier thanks for help changing the PR and getting it merged