[RI2 Ch01] Brief description of deployment scenarios
cntt-n/CNTT pull request #1948
Opened 2020-09-02 13:53 UTC by gkunz

This patch adds a brief overview of the deployment scenarios of RI2
and their impact on host provisioning.

Fixes #1791

Signed-off-by: Georg Kunz <georg.kunz@est.tech>

2020-09-02 13:59 UTC, tomkivlin requested changes

2020-09-02 13:59 UTC, tomkivlin commented on doc/ref_impl/cntt-ri2/chapters/chapter01.md
> +- **Deployment on an Infrastructure-as-aa-Service Layer**
```suggestion
- **Deployment on an Infrastructure-as-a-Service Layer**
```

2020-09-02 14:00 UTC, tomkivlin commented
As well as the three listed, should we include the ability for "any" infra to be used (i.e. if someone wants to provide their own) but then use the RI2 tooling to deploy Kubernetes + add-ons to that infrastructure.  So RI2 tooling wouldn't deploy the infra (which the current three options assume), but does deploy the k8s layer.

2020-09-02 14:58 UTC, gkunz commented
> As well as the three listed, should we include the ability for "any" infra to be used (i.e. if someone wants to provide their own) but then use the RI2 tooling to deploy Kubernetes + add-ons to that infrastructure. So RI2 tooling wouldn't deploy the infra (which the current three options assume), but does deploy the k8s layer.

Good point. Implicitly this is included in the general approach of having a host provision phase and a k8s deployment phase. So, the second phase should be runnable without the first one which is inline with my perspective. I'll check how to make this more clear in the text.

2020-09-03 11:18 UTC, tomkivlin approved these changes

2020-09-06 15:57 UTC, rihabbanday commented on doc/ref_impl/cntt-ri2/chapters/chapter01.md
> +Meaning, initially, the RI is not looking to have a single installer that can both build out virtual or physical machines **and** build out the Kubernetes and other components. The primary reason for
```suggestion
Meaning, initially, the RI is not looking to have a single installer that can both build out virtual or physical machines **and** build out the Kubernetes and other components. The primary reason for this was to ensure the loose coupling between the two layers, to drive the concept that RI2 is a standalone platform that can (in theory at least) be deployable to any infrastructure, whether that be some physical machines in a lab, or virtual machines in a private or public cloud environment, for example. From am implementation perspective, this means that the first step - infrastructure provisioning - needs to potentially support many different infrastructures and could even be an optional step in the overall end-to-end deployment process if an infrastructure is provided by other means. To tightly intertwine the deployment of machines and the Kubernetes platform with a single installer would potentially limit the locations on which the RI can be installed.
```

2020-09-09 09:27 UTC, michaelspedersen approved these changes
lgtm

2020-09-09 09:30 UTC, tomkivlin commented
@rihabbanday if you're happy with the changes made, could you approve please?  Should be able to merge then.

2020-09-09 09:56 UTC, rihabbanday approved these changes

2020-09-09 10:20 UTC, merged