[RA1 Ch02] Add RM Requirements
cntt-n/CNTT pull request #1949
Opened 2020-09-02 14:41 UTC by pgoyal01

Added RM requirements in 2.2
moved Security Requirements to 2.2.6

2020-09-04 15:16 UTC, karinesevilla reviewed
@pgoyal01 
In 2.2.1, capabilities description, "a single Pod " should be replaced by "a VM"

@karinesevilla Done - Thanks

2020-09-07 15:35 UTC, karinesevilla requested changes
@pgoyal01 some corrections:

2.2.1, Table 2-1:
e.cap.017 "n/a (3)" to be removed, it refers to containers and the associated note (3) to be removed
i.cap.014, i.cap.015, i.pm.001, i.pm.003: Replace "worker nodes" by "compute nodes"

2.2.2 Table 2.2: edition error, the 4 lines are duplicated

2.2.3
infra.com.cfg.002 Numa awareness for Basic must be "Not required"
infra.com.cfg.004 Huge Pages for Basic must be "Not required"
infra.net.acc.cfg.001 Remove Note (3) (K8s)
Note(1) Remove Pod
Remove Notes (2) and (3) K8s

2.2.4
Remove note (1) containers

2020-09-08 14:05 UTC, karinesevilla commented
@pgoyal01 Some modifications still remain

2.2.1, Table 2-1:
i.cap.014, i.cap.015, i.pm.001, i.pm.003: Replace "worker nodes" by "compute nodes"

2.2.3
infra.com.cfg.002: Numa awareness for Basic must be "Not required" ->the wrong column was changed,"description" rather than "Basic profile"

2020-09-08 14:33 UTC, karinesevilla approved these changes

2020-09-08 15:07 UTC, iangardner22 approved these changes

2020-09-08 15:07 UTC, iangardner22 approved these changes

2020-09-08 15:07 UTC, iangardner22 approved these changes

2020-09-09 12:23 UTC, walterkozlowski approved these changes

2020-09-09 13:54 UTC, scottsteinbrueck approved these changes

2020-09-09 14:20 UTC, merged