[RM CH02] Renumbering CH02 RM
cntt-n/CNTT pull request #1971
Opened 2020-09-07 12:29 UTC by ASawwaf

2020-09-07 12:43 UTC, TFredberg requested changes
ToC changed, but not the Chapter headings

2020-09-07 12:49 UTC, walterkozlowski approved these changes

2020-09-07 20:45 UTC, petorre approved these changes

2020-09-08 09:46 UTC, ulikleber requested changes
Chapter titles also need to be changed.

2020-09-09 13:42 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter02.md
> +* [2.4 Cloud Infrastructure Profiles](#2.3)
```suggestion
* [2.4 Cloud Infrastructure Profiles](#2.4)
```

2020-09-10 08:11 UTC, wmk-admin commented
@TFredberg, are you OK now with this PR and approving it?

2020-09-10 08:52 UTC, TFredberg commented
The ToC text is OK, but the links points to the wrong sub chapters.
The Sub chapters are numbered 2.1, 2.2, 2.2 and 2.3 which is wrong.

2020-09-10 10:49 UTC, closed without merging

2020-09-10 10:51 UTC, walterkozlowski commented
I am closing this PR and will make the changes appropriately in a different PR, using the latest merged contents.