[RM Ch07] Update CH07 with RA1 changes by @zwarico
cntt-n/CNTT pull request #2002
Opened 2020-09-12 23:19 UTC by pgoyal01

@zwarico made changes to Security requirements in RA1 and these also need to be made in RM (@walterkozlowski) and RA2 (@tomkivlin)

2020-09-13 01:11 UTC, walterkozlowski approved these changes

2020-09-13 16:27 UTC, collivier requested changes
Please add @zwarico as git author or as Co-Authored-By in git commit message.
PR title should not contain any author.

2020-09-13 22:23 UTC, petorre approved these changes

2020-09-14 03:11 UTC, walterkozlowski commented
@karinesevilla, can you please review and approve if possible? Thanks.

2020-09-14 07:17 UTC, tomkivlin commented
> @zwarico made changes to Security requirements in RA1 and these also need to be made in RM (@walterkozlowski) and RA2 (@tomkivlin)

#2009 created to deal with this.

2020-09-14 07:49 UTC, karinesevilla approved these changes

2020-09-14 07:52 UTC, TFredberg approved these changes

2020-09-14 08:25 UTC, merged