[RTD]: Using all sphinx extensions fomr pip
cntt-n/CNTT pull request #2069
Opened 2020-10-15 16:32 UTC by CsatariGergely

All the tree Sphinx modules implemented are moved out to separate projects and used from pip.

2020-10-22 12:54 UTC, walterkozlowski approved these changes

2021-01-13 19:07 UTC, tomkivlin approved these changes

2021-01-13 19:13 UTC, pgoyal01 approved these changes

2021-01-14 09:04 UTC, gkunz approved these changes

2021-01-14 09:17 UTC, ulikleber approved these changes

2021-01-15 08:53 UTC, collivier requested changes
Would it be possible to run pep8 and pylint on the py scripts (I quickly saw a couple of issues)?
It don't like so much defining concrete dependencies in requirements (I would prefer a PBR like design leveraging in upper-constraints to pin software version).

I would prefer not to merge with any pep8 and pylint issues. The upper-constraints part could be postponed if it helps.
Let me know if you need any help here.

2021-02-13 03:34 UTC, merged