[TSC RTD]: Remove width limitation of content
cntt-n/CNTT pull request #2072
Opened 2020-10-20 17:11 UTC by CsatariGergely

Fixes #2071

2020-10-22 12:56 UTC, walterkozlowski approved these changes

2021-01-13 18:58 UTC, tomkivlin approved these changes

2021-01-13 19:11 UTC, pgoyal01 approved these changes

2021-01-14 08:49 UTC, ulikleber approved these changes

2021-01-14 09:03 UTC, gkunz approved these changes

2021-01-16 13:46 UTC, tomkivlin commented on doc/_templates/layout.html
> +    <link href="{{ pathto("_static/custom.css", True) }}" rel="stylesheet" type="text/css">
Just noticed, does this path need `css/` in it?
```suggestion
    <link href="{{ pathto("_static/css/custom.css", True) }}" rel="stylesheet" type="text/css">
```

2021-01-16 17:17 UTC, collivier requested changes
At first glance, Tom's comment deserves an update

2021-02-13 03:33 UTC, merged