[RA1 Ch02] Update Network Resiliency Requirement
cntt-n/CNTT pull request #2101
Opened 2020-11-16 15:31 UTC by pgoyal01

Fixes #2061 
Clarify req.inf.ntw.07

2020-11-16 15:51 UTC, CsatariGergely requested changes

2020-11-16 15:51 UTC, CsatariGergely commented on doc/ref_arch/openstack/chapters/chapter02.md
> +| `req.inf.ntw.07` | Network | The Architecture **must** support network resiliency by maintaining an acceptable level of service in the face of faults and challenges to normal operation (from wikipe
```suggestion
| `req.inf.ntw.07` | Network | The Architecture **must** support network resiliency by [maintaining an acceptable level of service in the face of faults and challenges to normal operation](https://en.wikipedia.org/wiki/Resilience_(network)). | [RA-1 3.4.2.2. "Network"](./chapter03.md#3422-network) |
```

2020-11-16 16:07 UTC, pgoyal01 commented
@CsatariGergely Thanks. Accepted suggestion. Please review.

2020-11-18 18:59 UTC, pgoyal01 commented
Made changes as per suggestion by @petorre - Thanks. Replaced the added wording and wikipedia url with pointer to Glossary.

2020-11-18 19:06 UTC, petorre approved these changes

2020-11-19 09:06 UTC, ulikleber approved these changes

2020-11-23 14:40 UTC, pgoyal01 commented
@CsatariGergely Can you please re-review? Thanks

2020-11-24 05:48 UTC, sukhdevkapur approved these changes

2020-11-24 08:55 UTC, CsatariGergely approved these changes

2020-11-24 16:52 UTC, karinesevilla approved these changes

2020-11-30 01:17 UTC, merged