[RA2 Ch3] Memory management
cntt-n/CNTT pull request #2148
Opened 2020-12-21 15:20 UTC by petorre

Fixes #1918 .

2020-12-21 15:34 UTC, tomkivlin requested changes

2020-12-21 15:34 UTC, tomkivlin commented on doc/ref_arch/kubernetes/chapters/chapter03.md
>  already supported by upstream Kubernetes. For some applications, Huge Pages
Removing a duplication:

```suggestion
For some applications, Huge Pages
```

2020-12-21 18:09 UTC, pgoyal01 commented on doc/ref_arch/kubernetes/chapters/chapter03.md
> +For proper mapping of Huge Pages to scheduled pods, needed is to both have Huge Pages enabled in operating system (configured in kernel and mounted with correct permissions) and kubelet configuration
suggest language simplification:
```suggestion
For proper mapping of Huge Pages to scheduled pods, both need to have Huge Pages enabled in the operating system (configured in kernel and mounted with correct permissions) and kubelet configuration. Multiple sizes of Huge Pages can be enabled like 2 MiB and 1 GiB.
```

2020-12-21 21:53 UTC, pgoyal01 approved these changes

2021-01-05 14:56 UTC, tomkivlin approved these changes

2021-01-11 16:46 UTC, tomkivlin commented
@petorre could you resolve conflicts please, and then I'll merge.

2021-01-12 08:00 UTC, rgstori approved these changes

2021-01-12 10:03 UTC, petorre commented
> 
> 
> @petorre could you resolve conflicts please, and then I'll merge.

@tomkivlin : Done.

2021-01-12 10:05 UTC, merged