[RA2 Ch3] Scheduling pods with non-resilient apps
cntt-n/CNTT pull request #2154
Opened 2020-12-21 16:31 UTC by petorre

Fixes #2142 .

2020-12-21 16:36 UTC, tomkivlin requested changes

2020-12-21 16:36 UTC, tomkivlin commented on doc/ref_arch/kubernetes/chapters/chapter03.md
> +| 2 | Compute | Networking (dataplane) | CPU instructions | #1 plus NFD |
```suggestion
| 2 | Compute | Networking (dataplane) | CPU instructions | CPU Manager, NFD |
```

2020-12-21 16:36 UTC, tomkivlin commented on doc/ref_arch/kubernetes/chapters/chapter03.md
> +| 3 | Compute | Networking (dataplane) | Fixed function acceleration, Firmware-programmable network adapters or SmartNICs | #1 plus Device Plugin |
```suggestion
| 3 | Compute | Networking (dataplane) | Fixed function acceleration, Firmware-programmable network adapters or SmartNICs | CPU Manager, Device Plugin |
```

2020-12-21 16:36 UTC, tomkivlin commented on doc/ref_arch/kubernetes/chapters/chapter03.md
> +| 5 | Networking (dataplane) | | CPU instructions | #4 plus NFD |
```suggestion
| 5 | Networking (dataplane) | | CPU instructions | Huge Pages (for DPDK-based applications); CPU Manager with configuration for isolcpus and SMT; Multiple interfaces; NUMA topology; Device Plugin; NFD |
```

2020-12-21 16:36 UTC, tomkivlin commented on doc/ref_arch/kubernetes/chapters/chapter03.md
> +| 4 | Networking (dataplane) | | No, or Fixed function acceleration, Firmware-programmable network adapters or SmartNICs  | Huge Pages (for DPDK-based applications), CPU Manager with configuration fo
```suggestion
| 4 | Networking (dataplane) | | No, or Fixed function acceleration, Firmware-programmable network adapters or SmartNICs  | Huge Pages (for DPDK-based applications); CPU Manager with configuration for isolcpus and SMT; Multiple interfaces; NUMA topology; Device Plugin |
```

2020-12-21 17:58 UTC, pgoyal01 commented on doc/ref_arch/kubernetes/chapters/chapter03.md
> +<a name="3.2.1.8"></a>
Previous section is 3.2.1.5
```suggestion
<a name="3.2.1.6"></a>
```

2020-12-21 17:58 UTC, pgoyal01 commented on doc/ref_arch/kubernetes/chapters/chapter03.md
> +#### 3.2.1.8 Scheduling Pods with Non-resilient Applications
Previous section is 3.2.1.5
```suggestion
#### 3.2.1.6 Scheduling Pods with Non-resilient Applications
```

2020-12-21 18:04 UTC, pgoyal01 commented
@petorre The ToC needs to be changed with the new 3.2.1.6 (originally, 3.2.1.8)

2020-12-21 20:34 UTC, petorre commented
> 
> 
> @petorre The ToC needs to be changed with the new 3.2.1.6 (originally, 3.2.1.8)

Please see #2145 "Reorder 3.2.1.x sections and TOC".

2020-12-21 22:02 UTC, pgoyal01 approved these changes

2021-01-05 14:57 UTC, tomkivlin approved these changes

2021-01-12 08:01 UTC, rgstori approved these changes

2021-01-12 08:06 UTC, tomkivlin commented
@petorre could you resolve the conflicts and then I can merge. Thanks!

2021-01-12 09:58 UTC, petorre commented
> @petorre could you resolve the conflicts and then I can merge. Thanks!

Done.

2021-01-12 10:01 UTC, merged