[RM Ch3] HW Acceleration Resources
cntt-n/CNTT pull request #2158
Opened 2020-12-22 16:33 UTC by petorre

Towards fixing #2051 .

2021-01-05 08:28 UTC, CsatariGergely requested changes

2021-01-05 08:28 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.md
> +More details about Hardware Acceleration are in [Section 3.8 Hardware Acceleration Abstraction](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#3.8).
```suggestion
More details about Hardware Acceleration are in [Section 3.8 Hardware Acceleration Abstraction](chapter03.md#3.8).
```

2021-01-06 21:00 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter03.md
> +Hardware Accelerators can be used to offload software execution for purpose of accelerating tasks to achieve more or faster performance, or offloading them to another execution entity to get more pre
```suggestion
Hardware Accelerators can be used to offload software execution for purpose of accelerating tasks to achieve faster performance, or offloading the tasks to another execution entity to get more predictable execution times, efficient handling of the tasks or separation of authority regarding who can control the tasks execution.
```

2021-01-12 11:36 UTC, walterkozlowski commented
@petorre: I am approving but please make sure that the diagram is updated

2021-01-12 11:36 UTC, walterkozlowski approved these changes

2021-01-13 20:31 UTC, pgoyal01 approved these changes

2021-01-13 20:33 UTC, TFredberg approved these changes

2021-01-13 21:40 UTC, petorre commented
Added table caption as per agreement on RM call.

2021-01-14 10:36 UTC, merged