[RM Ch3] SmartNICs
cntt-n/CNTT pull request #2170
Opened 2020-12-22 17:50 UTC by petorre

Text from @TFredberg .
Towards fixing #2051 .

2021-01-04 10:11 UTC, CsatariGergely requested changes

2021-01-04 10:11 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.md
> +<p align="center"><img src="../figures/ch03-example-smartnic-deployment-model.png" alt="Example SmartNIC Deployment Model That Accelerates Two Workloads and Has OOB Management" Title="Example SmartNI
Add the .png file and its editable variant to the pr please.

2021-01-04 10:13 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.md
> +<p align="center"><img src="../figures/ch03-example-smartnic-deployment-model.png" alt="Example SmartNIC Deployment Model That Accelerates Two Workloads and Has OOB Management" Title="Example SmartNI
Okay, the png is added in #2169. I will comment my need for an editable version there.

2021-01-04 10:14 UTC, CsatariGergely approved these changes

2021-01-12 12:12 UTC, walterkozlowski approved these changes

2021-01-13 20:47 UTC, pgoyal01 approved these changes

2021-01-13 21:50 UTC, petorre commented
Resolved conflict.

2021-01-16 16:57 UTC, merged