[RM Ch3] SmartSwitches
cntt-n/CNTT pull request #2171
Opened 2020-12-22 17:55 UTC by petorre

Text from @qabpea .
Towards fixing #2051 .

2021-01-04 10:06 UTC, CsatariGergely requested changes
Can you please also describe what is the relationship of smart switches to RA2?

2021-01-04 10:06 UTC, CsatariGergely commented on doc/ref_model/chapters/chapter03.md
> +### 3.8.8 SmartSwitches
Why the camel case?

2021-01-06 20:38 UTC, petorre commented on doc/ref_model/chapters/chapter03.md
> +### 3.8.8 SmartSwitches
> 
> 
> Why the camel case?

Changed. Thanks

2021-01-07 16:42 UTC, petorre commented
> Can you please also describe what is the relationship of smart switches to RA2?

@qabpea : Maybe you could write this in one or two very concise sentences?
@CsatariGergely : This might need more work which would make it target for next release.

2021-01-12 12:13 UTC, walterkozlowski approved these changes

2021-01-12 12:14 UTC, walterkozlowski commented
@TFredberg, @sureshkrishnan, @qabpea - please review and approve if you can

2021-01-13 20:51 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter03.md
> +Smart Swiches can be broadly categorized into Configurable Switches and Programable Switches.
```suggestion
Smart Switches can be broadly categorized into Configurable Switches and Programmable Switches.
```

2021-01-13 20:52 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter03.md
> +Configurable Smart Switches run generic “smart” configurable network operating system offering full range of network functionality and are flexible enough to support most network solutions. The most
```suggestion
Configurable Smart Switches run generic “smart” configurable network operating system offering full range of network functionality and are flexible enough to support most network solutions. The most common such network operating system is Linux-based [SONiC](https://azure.github.io/SONiC/) allowing hardware and software disaggregation by running on switches from multiple switch vendors with different types of vendor fixed-function ASICs. Still, SONiC today cannot implement new type of data plane functionality or patch/modify/correct an ASIC, which is the type of support offered by programmable smart switches.
```

2021-01-13 20:54 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter03.md
> +Programable Smart Switches make it possible to quickly support new or correct/modify existing protocols and network functions, allow end customers to implement network functions, and to only implemen
```suggestion
Programmable Smart Switches make it possible to quickly support new or correct/modify existing protocols and network functions, allow end customers to implement network functions, and to only implement and load functionality that is needed. Such switches contain one or more programmable switch ASICs of the same or different types. The two most used programming languages are [P4](https://p4.org/) and [NPL](https://nplang.org/), and both can be used with vendor-specific toolchains to program their switch ASICs and/or FPGAs. Open Networking Foundation [Stratum](https://opennetworking.org/stratum/) is an example of network operating system that offers generic life cycle management control services for the P4 components and a management API. The control API for the individual network functions are not part of the Stratum APIs.
```

2021-01-13 20:56 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter03.md
> +Based on Smart Switches, for fully integrated edge and fabric products exist other solutions from vendors like Arista, Cisco or Kaloom.
there is something either missing or should be reworded
```suggestion
Based on Smart Switches, products exist for fully integrated edge and fabric solutions from vendors like Arista, Cisco or Kaloom.
```

2021-01-13 21:57 UTC, petorre commented
Resolved conflict.

2021-01-14 15:45 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter03.md
> +CPU architecture often includes instructions and execution blocks for most common compute-heavy algorithms like block cypher (example AES-NI), Random Number Generator or vector instructions. Those ar
```suggestion
The CPU architecture often includes instructions and execution blocks for most common compute-heavy algorithms like block cypher (example AES-NI), Random Number Generator or vector instructions. These functions are normally consumed in infrastructure software or applications by using enabled software libraries that run faster when custom CPU instructions for the execution of such functions are available in hardware and slower when these specific instructions are not available in hardware as only the general CPU instructions are used. Custom CPU instructions don’t need to be activated or life-cycle-managed. When scheduling workloads, compute nodes with such custom CPU instructions can be found by applications or an orchestrator using OpenStack Nova filters or Kubernetes Node Feature Discovery labels, or directly from the Hardware Management layer.
```

2021-01-14 17:58 UTC, TFredberg approved these changes

2021-01-15 15:28 UTC, pgoyal01 approved these changes

2021-01-16 16:53 UTC, collivier commented
@CsatariGergely @petorre : is the conflict resolved? It's well reviewed but I read "This might need more work which would make it target for next release".

2021-01-16 21:37 UTC, petorre commented
> @CsatariGergely @petorre : is the conflict resolved? It's well reviewed but I read "This might need more work which would make it target for next release".

@collivier : 
I resolved the conflicts.
Current text was prepared for Elbrus.
That comment meant that for more ideas we run out time to implement so those would go to next release. On February vF2F we have session for to discuss those.

2021-01-17 01:55 UTC, merged