[RM CH5] Minor editorial changes
cntt-n/CNTT pull request #2199
Opened 2021-01-18 11:28 UTC by EditKoselak

Closes #2113

2021-01-18 11:55 UTC, petorre approved these changes

2021-01-19 12:16 UTC, collivier approved these changes

2021-01-19 14:07 UTC, pgoyal01 requested changes
"number of CPU cores" should be listed as "number of cores per CPU"

2021-01-24 01:42 UTC, walterkozlowski commented
@EditKoselak please address change requested by @pgoyal01 and I will approve and merge the change after that

2021-01-25 11:17 UTC, EditKoselak commented
> "number of CPU cores" should be listed as "number of cores per CPU"

Thanks, we have corrected it:)

2021-01-26 18:09 UTC, pgoyal01 approved these changes

2021-01-27 23:35 UTC, merged