[RA2 Ch2,Ch4]: Kubernetes API feature requirements
cntt-n/CNTT pull request #2378
Opened 2021-04-29 08:16 UTC by CsatariGergely

Adding requirements to support all GA and beta Kubernetes features, but
to disable all Alpha features.

Closes #2349

2021-04-29 08:37 UTC, tomkivlin reviewed
Is it worth clarifying the relationship between feature gates and APIs?  e.g. to ensure we don't specify an Alpha feature gate in the spec, which in turn enables an Alpha API?

Or, do we need to also specify no Alpha feature gates, to ensure that those Feature Gates that don't relate to a new API (e.g. the [SuspendJob API](https://kubernetes.io/docs/concepts/workloads/controllers/job/#suspending-a-job) which enables a feature within the Batch API.

2021-04-29 15:23 UTC, CsatariGergely commented
> 
> 
> Is it worth clarifying the relationship between feature gates and APIs? e.g. to ensure we don't specify an Alpha feature gate in the spec, which in turn enables an Alpha API?
> 
> Or, do we need to also specify no Alpha feature gates, to ensure that those Feature Gates that don't relate to a new API (e.g. the [SuspendJob Feature Gate](https://kubernetes.io/docs/concepts/workloads/controllers/job/#suspending-a-job) which is Alpha, but enables a feature within the Batch API, which is not Alpha.

Hopefully clarified in bb11f9e

2021-05-13 10:06 UTC, rgstori requested changes

2021-05-13 10:06 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter02.md
> +| `req.int.api.03` | API | General | The Architecture **must** support stable features in its API-s. ||
```suggestion
| `req.int.api.03` | API | General | The Architecture **must** support stable features in its APIs. ||
```
typo: API-s to APIs

2021-05-13 10:06 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter02.md
> +| `req.int.api.03` | API | General | The Architecture **must** support limited backward compatibility in its API-s. Support for the whole API must not be dropped, but the schema or other details can
```suggestion
| `req.int.api.03` | API | General | The Architecture **must** support limited backward compatibility in its APIs. Support for the whole API must not be dropped, but the schema or other details can change. ||
```
typo

2021-05-13 10:06 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter04.md
> +|`ra2.k8s.012`|Kubernetes API-s|Kubernetes [Alpha API](https://kubernetes.io/docs/reference/using-api/#api-versioning) are recommended only for testing, therefore all Alpha API-s **must** be disabled
```suggestion
|`ra2.k8s.012`|Kubernetes APIs|Kubernetes [Alpha API](https://kubernetes.io/docs/reference/using-api/#api-versioning) are recommended only for testing, therefore all Alpha APIs **must** be disabled.|[req.int.api.03](./chapter02.md#22-reference-model-requirements)||
```

2021-05-13 10:06 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter04.md
> +|`ra2.k8s.013`|Kubernetes API-s|To provide backward compatibility all supported GA and Beta API-s of Kubernetes **must** be enabled. |[req.int.api.04](./chapter02.md#22-reference-model-requirements)|
```suggestion
|`ra2.k8s.013`|Kubernetes APIs|Backward compatibility of all supported GA and Beta APIs of Kubernetes **must** be supported. |[req.int.api.04](./chapter02.md#22-reference-model-requirements)||
```
clarified

2021-05-20 15:43 UTC, rgstori approved these changes

2021-05-20 19:24 UTC, petorre approved these changes

2021-05-23 05:56 UTC, walterkozlowski approved these changes

2021-05-23 05:56 UTC, merged