Add most of sigs in RA2 chapter 6
cntt-n/CNTT pull request #2400
Opened 2021-05-06 13:38 UTC by collivier

It remains sig-storage which asks for a deep dive on both features
and drivers. As starting point, the features list conforms with the
upstream K8s gates (kind).

It allows RA2 team to update the mandatory choices which RC2 will
conform. It's worth mentioning that a few related test could be still
skipped in RC2 (only for gce, disruptive, alpha, etc.).

Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>

2021-05-06 15:16 UTC, rgstori approved these changes

2021-05-10 10:02 UTC, CsatariGergely requested changes

2021-05-13 15:40 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter06.md
> +| None                         | X             |
these are labels. "None" selects all functest objects that have the label "none".

2021-05-20 15:31 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter06.md
> +| Conformance                  | X             |
these are labels. "Conformance" selects all functest objects that have the label "Conformance".

2021-05-20 15:32 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter06.md
> +| None                         | X             |
"Conformance" means it's in the k8s conformance test, and "None" means mainstream features

2021-05-20 15:32 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter06.md
> +| Conformance                  | X             |
"Conformance" means it's in the k8s conformance test, and "None" means mainstream features

2021-05-24 10:49 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter06.md
> +| Feature:NetworkPolicy               |               |
let's add one to chapter 4 first then, then add the `X` here with a new PR 
(or not)

2021-05-24 10:50 UTC, rgstori commented on doc/ref_arch/kubernetes/chapters/chapter06.md
> +| Feature:StatefulSet          |               |
yes, let's add this to a new PR though (including adding columns for the description of each feature in plain English and the traceability to ch4 specs)

2021-05-24 10:51 UTC, rgstori approved these changes

2021-05-24 11:06 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter06.md
> +| Conformance                  | X             |
Can we have an explanation of this in the intro chapter? I'm okay to have this in an other pr.

2021-05-24 11:07 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter06.md
> +| Feature:StatefulSet          |               |
Okey. Should I create an issue to capture this?

2021-05-27 15:26 UTC, pgoyal01 approved these changes

2021-05-27 15:28 UTC, karinesevilla approved these changes

2021-05-27 15:28 UTC, merged