[RM Ch04] Obsolete CNTT policies
cntt-n/CNTT pull request #2407
Opened 2021-05-07 09:41 UTC by karinesevilla

Fixes issue #2352 
Obsolete CNTT policies
In Table 4-2, text mentioning prohibition of features requiring workloads hardware-dependent code has been removed for e.cap.013 to e.cap.016

2021-05-07 16:17 UTC, petorre approved these changes

2021-05-12 08:23 UTC, walterkozlowski approved these changes

2021-05-12 13:59 UTC, pgoyal01 requested changes
Approved but it needs CNTT Policies to be changed:
- Common: [Hardware Dependent Coding](https://github.com/cntt-n/CNTT/blob/master/doc/common/policies.md#hardware-dependent-coding) 
- Common: [Current CNTT Policies](https://github.com/cntt-n/CNTT/blob/master/doc/common/policies.md#current-cntt-policies)
- Common: [SR-IOV over PCI-PT](https://github.com/cntt-n/CNTT/blob/master/doc/common/policies.md#sr-iov-over-pci-pt)

Issue #2418 opened

2021-05-12 14:21 UTC, pgoyal01 approved these changes

2021-05-13 01:10 UTC, merged