Fixes #2501: Replace CNTT with Anuket
cntt-n/CNTT pull request #2522
Opened 2021-07-01 04:40 UTC by msidana

2021-07-01 05:18 UTC, walterkozlowski approved these changes

2021-07-01 05:31 UTC, pgoyal01 commented on CONTRIBUTING.md
> +* [Contribution Guidelines](https://github.com/cntt-n/Anuket CNTT/wiki/Contribution-Guidelines)
You can't do this -- there is no such link

2021-07-01 05:31 UTC, pgoyal01 commented on CONTRIBUTING.md
> +* [Approval Process](https://github.com/cntt-n/Anuket CNTT/wiki/Approval-Process)
You can't do this -- there is no such link

2021-07-01 05:34 UTC, pgoyal01 commented on .github/ISSUE_TEMPLATE/cntt-issue.md
> +name: Anuket CNTT Issue
Why are we referring to "Anuket CNTT" as there is no such entity. APplies to many other changes.

2021-07-01 05:35 UTC, pgoyal01 commented on CONTRIBUTING.md
> +There are different permissions (levels) available for contributing into Anuket CNTT:
```suggestion
There are different permissions (levels) available for contributing to Anuket:
```

2021-07-01 05:36 UTC, pgoyal01 commented on CONTRIBUTING.md
> +Every Issue and PR should be tagged with one or more of the following labels to indicate their status and for the automation pipelines to apply the correct Anuket CNTT processes.
```suggestion
Every Issue and Patch Request (PR) should be tagged with one or more of the following labels to indicate their status and for the automation pipelines to apply the correct Anuket processes.
```

2021-07-01 05:41 UTC, pgoyal01 commented on README.md
> +* [Term of Reference](GSMA_Anuket CNTT_Terms_of_Reference.pdf)
```suggestion
* [Term of Reference](GSMA_CNTT_Terms_of_Reference.pdf)
```

2021-07-01 05:41 UTC, pgoyal01 commented on README.md
> +* [Wiki](https://github.com/cntt-n/Anuket CNTT/wiki)
```suggestion
* [Wiki](https://github.com/cntt-n/CNTT/wiki)
```

2021-07-01 05:42 UTC, pgoyal01 commented on README.md
> +# Cloud iNfrastructure Telco Task Force (Anuket CNTT)
```suggestion
# Cloud iNfrastructure Telco Task Force (CNTT)
```

2021-07-01 05:42 UTC, pgoyal01 commented on doc/README.md
> +  * [Terms of Reference](../GSMA_Anuket CNTT_Terms_of_Reference.pdf)
```suggestion
  * [Terms of Reference](../GSMA_CNTT_Terms_of_Reference.pdf)
```

2021-07-01 05:47 UTC, pgoyal01 requested changes
@msidana 
1. You can't change URLs or file names by prefixing "CNTT" with "Anuket ". They will result in errors. I have pointed this out in some places but the number of such changes is quite large.
1. Except where CNTT is defined or is relevant from a historical perspective you should replace CNTT with Anuket but not Anuket CNTT -- CNTT doesn't exist anymore.

@walterkozlowski This should not be approved at least until all url's and file names are restored.

2021-07-01 06:07 UTC, msidana commented
> @msidana
> 
> 1. You can't change URLs or file names by prefixing "CNTT" with "Anuket ". They will result in errors. I have pointed this out in some places but the number of such changes is quite large.
> 2. Except where CNTT is defined or is relevant from a historical perspective you should replace CNTT with Anuket but not Anuket CNTT -- CNTT doesn't exist anymore.
> 
> @walterkozlowski This should not be approved at least until all url's and file names are restored.

@pgoyal01 I had not done the change at a few places to avoid breaking links/urls but some still made way due to overall replacement. I'll fix this to ensure there are no broken URLs. Within the repo, I have addressed this by changing filenames so that the linking doesn't breaks. Will update the PR and push again.

2021-07-02 10:16 UTC, CsatariGergely commented
@msidana thanks for the pr, but you can not just replace "CNTT" with "Anuket" in every file. Please create a pr per document, like RM, RA1, RA2 and so on and "Anuket CNTT" is not a think, also if you replace CNTT to anything else in the absuolte links the links will break (instead please replace the absolulte links to relative ones ). I would propose to close this pr and open specific pr-s to the different document. @EditKoselak is also working on the Annuket-ization so please align with her on what documents you would like to address.

2021-07-06 06:52 UTC, closed without merging