[docs] Applying the Sphinx material theme
cntt-n/CNTT pull request #2652
Opened 2021-10-12 21:42 UTC by gkunz

As part of the transition from markdown to rst, this PR applies
the material theme which provides a local and global table of content.

Fixes #2617

Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

2021-11-04 10:04 UTC, walterkozlowski approved these changes

2021-11-04 13:58 UTC, ildikov approved these changes

2021-11-30 12:24 UTC, CsatariGergely commented on requirements.txt
> +sphinx==2.1.0
Uh oh, I will check how to resolve that conflict. 
We will not need relative-link-corrector once we use native rst.

2021-11-30 13:39 UTC, CsatariGergely commented on requirements.txt
> +sphinx==2.1.0
Fix proposed here: https://github.com/cntt-n/sphinxcontrib-relative-link-corrector/pull/4

2021-12-01 11:17 UTC, gkunz commented on requirements.txt
> +sphinx==2.1.0
I noticed that the relative-link-corrector already supported this (with a small bug) in version 0.0.4, but the requirements file for our docs was still pulling in 0.0.3.

2021-12-01 12:20 UTC, CsatariGergely commented on requirements.txt
> +sphinx==2.1.0
yes, that bug I fix in cntt-n/sphinxcontrib-relative-link-corrector#4 :)

2021-12-01 12:37 UTC, CsatariGergely commented on requirements.txt
> +sphinx==2.1.0
And 0.0.5 is released now :)

2021-12-01 13:04 UTC, gkunz commented on requirements.txt
> +sphinx==2.1.0
bumped to 0.0.5

2021-12-01 13:36 UTC, CsatariGergely approved these changes

2021-12-09 13:56 UTC, collivier commented
Please see tox + *requirements.txt in https://github.com/cntt-n/CNTT/pull/2741
https://github.com/cntt-n/CNTT/pull/2741/files#diff-d0c24725a770ee24898050e5ccd7d04d272887b30c1635c423c905ac497e8795R8
https://github.com/cntt-n/CNTT/pull/2741/files#diff-52c2b819893b2d6585f2a179023463d0b246ec8ca86bbe00920c772f6375180b

2021-12-09 13:57 UTC, collivier requested changes
Please see previous comment

2022-01-18 15:01 UTC, pgoyal01 commented
@gkunz There is a comment from @collivier and a conflicting file. After resolution, you should request @walterkozlowski to merge. Thanks

2022-01-19 22:43 UTC, pgoyal01 approved these changes

2022-01-20 13:37 UTC, rihabbanday approved these changes

2022-02-17 08:39 UTC, gkunz commented
@collivier kind reminder

2022-03-01 16:52 UTC, pgoyal01 approved these changes

2022-03-01 17:51 UTC, steelescotr approved these changes

2022-03-07 13:35 UTC, gkunz commented
@collivier kind reminder. Thanks

2022-03-28 15:19 UTC, collivier commented on test-requirements.txt
> +sphinx!=1.6.6,!=1.6.7,!=2.1.0,!=3.0.0,!=3.4.2,<3 # BSD
Here it's the official abstract deps proposed by OpenStack and I would suggest no to change it.

2022-04-28 12:32 UTC, merged

2022-05-03 07:58 UTC, collivier commented
@CsatariGergely @gkunz All doc builds are now broken.