[RI2] proofreading and removal of some HTML tags
cntt-n/CNTT pull request #2678
Opened 2021-11-03 15:36 UTC by gkunz

Partially closes #2603

Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

2021-11-04 10:39 UTC, CsatariGergely requested changes

2021-11-04 10:39 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri2/chapters/chapter01.md
> +![State](../figures/bogo_dfp.png)
```suggestion
![State](../figures/bogo_dfp.png) <!-- width="35" -->
```
Let's use this notation for now, so we have a chance to scale the images during the rst conversion.

2021-11-04 10:39 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri2/chapters/chapter03.md
> +![State](../figures/bogo_lsf.png)
```suggestion
![State](../figures/bogo_lsf.png) <!-- width="35" -->
```

2021-11-04 10:39 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri2/chapters/chapter04.md
> +![State](../figures/bogo_sdc.png)
```suggestion
![State](../figures/bogo_sdc.png) <!-- width="35" -->
```

2021-11-04 10:39 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri2/chapters/chapter05.md
> +![State](../figures/bogo_ifo.png)
```suggestion
![State](../figures/bogo_ifo.png) <!-- width="35" -->

```

2021-11-04 13:03 UTC, CsatariGergely approved these changes

2021-11-04 14:02 UTC, ildikov reviewed
A few nits/questions in line, otherwise looks good.

Thanks,
Ildikó

2021-11-04 14:02 UTC, ildikov commented on doc/ref_impl/cntt-ri2/chapters/chapter01.md
> +- **Compliance and Verification Committee & Anuket Assured**
Anuket Assured Program?

2021-11-04 14:02 UTC, ildikov commented on doc/ref_impl/cntt-ri2/chapters/chapter03.md
> +﻿# 3. Requirements for Labs
Lab Requirements

2021-11-04 17:19 UTC, gkunz commented on doc/ref_impl/cntt-ri2/chapters/chapter01.md
> +In order to promote the quick deployment of the RI and avoid duplicating effort across communities, the RI community works closely with CNCF TUG, Anuket Assured, ONAP and TIP communities.
included

2021-11-04 17:19 UTC, gkunz commented on doc/ref_impl/cntt-ri2/chapters/chapter01.md
> +- **Compliance and Verification Committee & Anuket Assured**
included

2021-11-04 17:19 UTC, gkunz commented on doc/ref_impl/cntt-ri2/chapters/chapter03.md
> +﻿# 3. Requirements for Labs
fixed

2021-11-12 08:24 UTC, gkunz commented
Kind review reminder. Thanks.

2021-11-12 09:23 UTC, rihabbanday approved these changes

2021-11-12 15:14 UTC, pgoyal01 approved these changes

2021-11-15 21:42 UTC, merged