[RA1 Ch01] Correct OVP Phase 2
cntt-n/CNTT pull request #2681
Opened 2021-11-04 16:15 UTC by pgoyal01

Fixes #2350

2021-11-04 16:44 UTC, gkunz requested changes

2021-11-04 16:44 UTC, gkunz commented on doc/ref_arch/kubernetes/chapters/chapter01.md
> +The Kubernetes Reference Architecture will be used to determine a Kubernetes Reference Implementation. The Kubernetes Reference Implementation would then also be used to test and validate the support
"the OpenStack Anuket project" is confusing. A suggestion below.

```suggestion
The Kubernetes Reference Architecture will be used to determine a Kubernetes Reference Implementation. The Kubernetes Reference Implementation would then also be used to test and validate the supportability and compatibility with Kubernetes-based Network Function workloads, and lifecycle management of Kubernetes clusters, of interest to the Anuket community. It is expected that the Kubernetes Reference Architecture, Reference Implementation, and Reference Conformance will be developed building on the work already in place for OpenStack in the Anuket project. The intention is to expand as much of the existing test frameworks to be used for the verification and conformance testing of Kubernetes-based workloads, and Kubernetes cluster lifecycle management.
```

2021-11-04 16:46 UTC, pgoyal01 commented
@gkunz Thanks - done.

2021-11-04 16:53 UTC, gkunz approved these changes

2021-11-11 15:17 UTC, rgstori approved these changes

2021-11-11 15:17 UTC, rgstori commented
@walterkozlowski can you please approve and merge?

2021-11-12 08:49 UTC, ulikleber approved these changes

2021-11-12 14:18 UTC, merged