[RM Ch04] Proofreading
cntt-n/CNTT pull request #2721
Opened 2021-11-12 19:37 UTC by pgoyal01

Fixes #2715

2021-11-12 19:43 UTC, ildikov commented on doc/ref_model/chapters/chapter04.md
> +**Exposed:** Refers to any object (e.g., resource discovery/configuration/consumption, platform telemetry, interface, etc.) that exists in or pertains to, the domain of the Cloud Infrastructure and i
```suggestion
**Exposed:** Refers to any object (e.g., resource discovery/configuration/consumption, platform telemetry, interface, etc.) that exists in or pertains to, the domain of the Cloud Infrastructure and is made visible (aka “Exposed”) to a workload. When an object is exposed to a given workload, the scope of visibility within a given workload is at the discretion of the workload’s designer. From an infrastructure perspective, the Infra-resident object is simply being exposed to one or more virtual environments (i.e., workloads). It is the responsibility of the kernel or supervisor/executive within the resource instance (VM or container) to control how, when and where the object is further exposed within the resource instance, with regard to permissions, security, etc. An object(s) is by definition visible within its domain of origin.
```

2021-11-12 19:46 UTC, ildikov commented on doc/ref_model/chapters/chapter04.md
> +The Cloud Infrastructure Manager (CIM) is responsible for controlling and managing the Cloud Infrastructure compute, storage, and network resources. Resources are dybamically allocated based on workl
```suggestion
The Cloud Infrastructure Manager (CIM) is responsible for controlling and managing the Cloud Infrastructure compute, storage, and network resources. Resources are dybamically allocated based on workload requirements. This section covers the list of capabilities offered by the CIM to workloads or service orchestrator.
```

2021-11-12 19:48 UTC, ildikov reviewed
Just two small suggestions.

Thanks,
Ildikó

2021-11-12 19:52 UTC, ildikov approved these changes

2021-11-13 09:11 UTC, walterkozlowski approved these changes

2021-11-14 01:47 UTC, walterkozlowski commented
@karinesevilla, @jbhartley - can you please review as well? Thanks.

2021-11-14 22:22 UTC, gkunz requested changes
two spelling corrections

2021-11-14 22:22 UTC, gkunz commented on doc/ref_model/chapters/chapter04.md
> +**Table 4-1** below shows resource capabilities of the Cloud Infrastructure avaiiable to workloads.
```suggestion
**Table 4-1** below shows resource capabilities of the Cloud Infrastructure available to workloads.
```

2021-11-14 22:22 UTC, gkunz commented on doc/ref_model/chapters/chapter04.md
> +The Cloud Infrastructure Manager (CIM) is responsible for controlling and managing the Cloud Infrastructure compute, storage, and network resources. Resources are dybamically allocated based on workl
```suggestion
The Cloud Infrastructure Manager (CIM) is responsible for controlling and managing the Cloud Infrastructure compute, storage, and network resources. Resources are dynamically allocated based on workload requirements. This section covers the list of capabilities offered by the CIM to workloads or service orchestrator.
```

2021-11-15 01:16 UTC, pgoyal01 commented
@gkunz Done - Thanks

2021-11-15 01:42 UTC, walterkozlowski commented
@gkunz, fixed I can see.  Thanks!

2021-11-15 01:54 UTC, walterkozlowski commented
@pgoyal01, can you please resolve the conflict?  Thanks.

2021-11-15 05:53 UTC, pgoyal01 commented
@walterkozlowski Resolved the conflicts. Thanks

2021-11-15 06:06 UTC, walterkozlowski commented
@gkunz, can you please re-review and approve, if you can, thanks

2021-11-15 07:40 UTC, gkunz approved these changes

2021-11-15 07:44 UTC, ulikleber approved these changes

2021-11-15 09:52 UTC, merged