[RI1] Conversion to rst
cntt-n/CNTT pull request #2777
Opened 2021-12-29 21:37 UTC by gkunz

This PR converts the RI1 documentation from markdown to rst.

2021-12-30 11:37 UTC, CsatariGergely requested changes

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +|                                                 | types <ref_arch/openstack/chapters/chapter04#4.4.1>`                                                                                              |
```suggestion
|                                                 | types <../../../ref_arch/openstack/chapters/chapter04.md#4.4.1>`__                                                                                |```

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter06.rst
> +.. _installer-requirements-1:
```suggestion
.. _ri1-ch6-requirements:
```

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter06.rst
> +.. _server-information-1:
```suggestion
.. _ri1-ch6server-information:
```

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +
Please add caption

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +.. _access--connectivity:
```suggestion
.. _ri1-ch8-access--connectivity:
```

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +.. _opnfv-descriptor-files-1:
```suggestion
.. _ri1-ch8-opnfv-descriptor-files:
```

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +.. _deployment-installer--install-steps:
```suggestion
.. _ri1-ch8-deployment-installer--install-steps:
```

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +.. _jenkins-setup--job-creation:
```suggestion
.. _ri1-ch8-jenkins-setup--job-creation:
```

2021-12-30 11:37 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter09.rst
> +.. _traffic-generators--nic:
```suggestion
.. _ri1-ch9-traffic-generators--nic:
```

2021-12-30 17:18 UTC, pgoyal01 commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +Any virtual network functions and/or cloud-native network functions must choose to run on one of the pre-defined of entries in Cloud Infrastructure Infrastructure Profiles Catalogue. As states in `RM
@CsatariGergely in your suggested change should the "." be also deleted?

2021-12-30 17:18 UTC, pgoyal01 commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +B/N is used to specify the instance type (Basic, Network Intensive), different instance types are associated with different acceleration extensions, network characteristics (`RM: Profiles Specificati
same comment as before about the "."

2021-12-30 17:19 UTC, pgoyal01 commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +`RM: 5.2 Cloud Infrastructure Software Profiles features and requirements <https://cntt.readthedocs.io/en/latest/ref_model/chapters/chapter05.html#cloud-infrastructure-software-profiles-features-and-
delete the "."

2021-12-30 23:05 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter01.rst
> +Terminology in this document will follow :doc:`common/glossary`.
the doc directive makes use of the intersphinx mapping defined in the local conf. Actually, when applying the suggested change, the build fails for me.

2021-12-30 23:07 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +.. _cloud-infrastructure--vnf-target-state--specification:
I am sorry for leaving those in the rst files. They were created by pandoc, but I assumed we were going to use implicit section header references. So, I would rather like to remove all those explicit anchors.

2021-12-30 23:09 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +.. _opnfv-descriptor-files-1:
see above: I'd like to remove this.

2021-12-30 23:09 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +.. _deployment-installer--install-steps:
see above: I'd like to remove this.

2021-12-30 23:09 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter09.rst
> +.. _traffic-generators--nic:
see above: I'd like to remove this.

2021-12-30 23:09 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +.. _jenkins-setup--job-creation:
see above: I'd like to remove this.

2021-12-30 23:10 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter08.rst
> +.. _access--connectivity:
see above: I'd like to remove this.

2021-12-30 23:16 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +Any virtual network functions and/or cloud-native network functions must choose to run on one of the pre-defined of entries in Cloud Infrastructure Infrastructure Profiles Catalogue. As states in `RM
I agree with using the ref directive. The configuration for building RI1 individually was missing the link corrector and hence the links broke for me. I'll try to address that.

2022-01-03 08:58 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter01.rst
> +Terminology in this document will follow :doc:`common/glossary`.
1. I was using `tox` from the top level directory. Should we agree to craft document specific `tox.ini`-s and build locally?
2. I was not aware that intersphinx can do this :)

2022-01-03 09:01 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +.. _cloud-infrastructure--vnf-target-state--specification:
I'm okay with removing them, but I could not find a way to refer to the implicit section header references. Do you have a working example?

2022-01-03 09:03 UTC, CsatariGergely commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +Any virtual network functions and/or cloud-native network functions must choose to run on one of the pre-defined of entries in Cloud Infrastructure Infrastructure Profiles Catalogue. As states in `RM
> @CsatariGergely in your suggested change should the "." be also deleted?

Not from the filenames. (I assume you refer to the . in `chapter04.md`)

2022-01-04 15:26 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +.. _cloud-infrastructure--vnf-target-state--specification:
For intra-references using implicit header references, see https://github.com/cntt-n/CNTT/pull/2777/files#diff-774fcc11722dce98d0347ce9870d8c0959a06c61223d2ee4a1cc4516db7211b5R64

You have to use the autosectionlabel extention (see https://github.com/cntt-n/CNTT/pull/2777/files#diff-e59005d178179a798a25d32c0f18a66b77b4cd290462ac82d5594c23fb0ee0d6R15)

2022-01-04 16:01 UTC, gkunz commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +Any virtual network functions and/or cloud-native network functions must choose to run on one of the pre-defined of entries in Cloud Infrastructure Infrastructure Profiles Catalogue. As states in `RM
> @CsatariGergely in your suggested change should the "." be also deleted?

@pgoyal01 which "." are you referring to?

2022-01-04 17:22 UTC, pgoyal01 commented on doc/ref_impl/cntt-ri/chapters/chapter03.rst
> +Any virtual network functions and/or cloud-native network functions must choose to run on one of the pre-defined of entries in Cloud Infrastructure Infrastructure Profiles Catalogue. As states in `RM
This sentence needs to be corrected as pre-defined profiles or the catalogue doesn't exist. Also, should the section number "4.2" be deleted in the text.

Opened Issue #2780.

2022-01-18 14:39 UTC, pgoyal01 approved these changes

2022-01-18 14:40 UTC, pgoyal01 commented
There needs to be an issue to correct CNTT, OPNFV, etc.

2022-02-23 11:17 UTC, walterkozlowski approved these changes

2022-02-23 11:19 UTC, walterkozlowski approved these changes

2022-03-14 14:39 UTC, gkunz commented
@CsatariGergely can you please re-view? In its current version, all checks are passing. I'd like to keep this PR concise and address the following in follow-up PRs: rename OPNFV to Anuket, replace links to rtd with intersphinx links.

2022-03-16 08:54 UTC, merged