Update CODEOWNERS
cntt-n/CNTT pull request #2782
Opened 2022-01-05 15:23 UTC by rihabbanday

Add Scot Steele as RC2 owner

2022-01-05 15:24 UTC, pgoyal01 approved these changes

2022-01-05 15:24 UTC, michaelspedersen approved these changes

2022-01-05 17:32 UTC, pgoyal01 commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter01.md        @walterkozlowski @ss8171
```suggestion
/doc/ref_cert/RC2/chapters/chapter01.md        @walterkozlowski @steelescotr
```

2022-01-05 17:33 UTC, pgoyal01 commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter03.md        @walterkozlowski @ss8171
```suggestion
/doc/ref_cert/RC2/chapters/chapter03.md        @walterkozlowski @steelescotr
```

2022-01-05 17:33 UTC, pgoyal01 commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter05.md        @walterkozlowski @ss8171
```suggestion
/doc/ref_cert/RC2/chapters/chapter05.md        @walterkozlowski @steelescotr
```

2022-01-05 17:34 UTC, pgoyal01 commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter04.md        @walterkozlowski @ss8171
```suggestion
/doc/ref_cert/RC2/chapters/chapter04.md        @walterkozlowski @steelescotr
```

2022-01-05 17:34 UTC, pgoyal01 commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter06.md        @walterkozlowski @ss8171
```suggestion
/doc/ref_cert/RC2/chapters/chapter06.md        @walterkozlowski @steelescotr
```

2022-01-05 17:34 UTC, pgoyal01 commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter07.md        @walterkozlowski @ss8171
```suggestion
/doc/ref_cert/RC2/chapters/chapter07.md        @walterkozlowski @steelescotr
```

2022-01-05 17:34 UTC, pgoyal01 commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter08.md        @walterkozlowski @ss8171
```suggestion
/doc/ref_cert/RC2/chapters/chapter08.md        @walterkozlowski @steelescotr
```

2022-01-05 17:34 UTC, pgoyal01 commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter09.md        @walterkozlowski @ss8171
```suggestion
/doc/ref_cert/RC2/chapters/chapter09.md        @walterkozlowski @steelescotr
```

2022-01-05 17:37 UTC, pgoyal01 approved these changes

2022-01-05 17:40 UTC, gkunz requested changes

2022-01-05 17:40 UTC, gkunz commented on CODEOWNERS
> +/doc/ref_cert/RC2/chapters/chapter09.md        @walterkozlowski @steelescotr
How about simplifying this like the following:

```suggestion
/doc/ref_cert/RC2/        @walterkozlowski @steelescotr
```

2022-01-05 17:55 UTC, pgoyal01 commented
@gkunz should all other entries be similarly changed?

2022-01-05 18:47 UTC, gkunz commented
> @gkunz should all other entries be similarly changed?

I think that would be a good idea.

2022-01-05 19:30 UTC, pgoyal01 commented
@gkunz Done - Thanks

2022-01-05 22:35 UTC, gkunz requested changes
Thanks for updating the other sections as well. There is one syntax issue left.

2022-01-05 22:35 UTC, gkunz commented on CODEOWNERS
> +/doc/tech/usecases.md        @ASawwaf @walterkozlowski --->
I believe the correct character for comments is '#'

```suggestion
# Edge workstream
# /doc/tech/usecases.md              @ASawwaf @walterkozlowski
```

2022-01-05 23:08 UTC, gkunz approved these changes

2022-01-06 06:54 UTC, walterkozlowski approved these changes

2022-01-06 06:54 UTC, merged