[Rm ChALL] Correct Figure captions for rst - WIP
cntt-n/CNTT pull request #2880
Opened 2022-03-21 03:46 UTC by pgoyal01

Partially Fixes #2875

still in WIP 

Only Ch 01 complete

2022-03-23 17:13 UTC, pgoyal01 commented
@cntt-n/ref-m This PR is now ready for review. Thanks

2022-03-23 19:08 UTC, gkunz requested changes
When building RM separately, the linter throws three errors. See the log of Cedric's automated check. I have indicated fixes for two.
The third error indicates that you need to rebase your PR because the current parent is _before_ the merged patch which fixes this error and _before_ the one which enables numfig.

2022-03-23 19:08 UTC, gkunz commented on doc/ref_model/chapters/chapter07.rst
>  .. image:: ../figures/ch7-data-access-model.png
Fixing linting error:
```
./chapters/chapter07.rst:145: D000 Error in "image" directive:
no content permitted.
```

```suggestion
.. figure:: ../figures/ch7-data-access-model.png
```

2022-03-28 07:32 UTC, gkunz reviewed
LGTM, but there is one more instance of a non-numref reference to a figure in chapter3, line 274 (don't know why I cannot link to this)

2022-03-28 13:10 UTC, gkunz approved these changes
LGTM

2022-03-30 16:07 UTC, karinesevilla commented on doc/ref_model/chapters/chapter01.rst
> +.. _Fig-1-1:
@pgoyal01 For the reference definition, I have a doubt about the writing and the underscore, would it not be .. _Fig-1-1 ?

2022-03-31 12:48 UTC, karinesevilla commented on doc/ref_model/chapters/chapter01.rst
> +.. _Fig-1-1:
@pgoyal01 Agree with the format per documentation. I am seeing the text underlined, but it seems to be a bad effect of display. In your original file, it is correct, so do not take into account my comment.

2022-03-31 12:48 UTC, karinesevilla commented on doc/ref_model/chapters/chapter02.rst
> +.. _Fig-2-5:
@pgoyal01 it is correct, so do not take into account my comment.

2022-03-31 13:47 UTC, karinesevilla commented on doc/ref_model/chapters/chapter05.rst
> +   :alt: "FCloud Infrastructure software layers"
@pgoyal01 typo: FCloud

2022-03-31 13:54 UTC, karinesevilla commented on doc/ref_model/chapters/chapter08.rst
> +As outlined in :numref:`Conceptual Architecture of a Telco Operator Platform" above, the exposure point for the Management Interactions is the "Cloud Service Broker" and the "Cloud Resource Broker".
@pgoyal01 Typo `Conceptual Architecture of a Telco Operator Platform"

2022-03-31 15:02 UTC, karinesevilla approved these changes

2022-04-01 15:04 UTC, ulikleber approved these changes

2022-04-06 13:06 UTC, walterkozlowski approved these changes

2022-04-06 13:06 UTC, merged

2022-04-06 13:41 UTC, collivier commented
@walterkozlowski the gate voted -1 because they are issues in figure descriptions. I just fixed them.