[docs] fix for Jinja2 3.2.0 breaking builds with old versions of Sphinx
cntt-n/CNTT pull request #2892
Opened 2022-03-25 11:02 UTC by gkunz

A recent update of Jinja2 breaks builds using the old version of Sphinx we are
using. We still use Sphinx < 2 to build the overall documentation containing
both markdown and rst files. Newer versions seem to have problems with this.

Once all files have been converted to rst, we can uplift Sphinx (see individual
builds which already today use much newer versions of Sphinx).

See also readthedocs/readthedocs.org#9037

As a temporary solution, I suggest to limit jinja2 to < 3.2.0 until we can
remove the version restriction in the overall build.

Fixes #2891

Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

2022-03-30 21:02 UTC, gkunz commented
@CsatariGergely, @collivier can you confirm this locally? rtd seems to have a fix in place, but when building all specs from the root, the build fails for me. Thanks

2022-04-05 12:38 UTC, collivier requested changes
Sorry I would frankly prefer we ask for sphinx > 4 as done in ONAP.
RTD leverages project date creation as I reported to ONAP and to CNTT.

2022-04-05 12:40 UTC, collivier commented
I think we do consider removing obsolete sphinx ext when we get rid of md. This package may disappear from our requirements.txt.

Very convinced by updating Shinx and get rid of useless deps.

2022-04-05 12:47 UTC, gkunz commented
@collivier: agree, this is just a temporary fix and not so pressing since the build works on rtd. I support getting the conversion done and finally uplifting Sphinx.

2022-04-22 10:48 UTC, CsatariGergely approved these changes

2022-04-22 13:36 UTC, gkunz commented
@collivier it would be helpful to merge this as a temporary solution to enable builds of the entire documentation. Keeping the repo in a broken state is not ideal. So, kindly asking for a re-review.

@walterkozlowski this fixes broken builds as reported by @CsatariGergely and me.

Thanks

2022-04-22 15:52 UTC, pgoyal01 approved these changes

2022-04-27 10:15 UTC, gkunz commented
@walterkozlowski can you please review? Thank you!

2022-05-06 20:10 UTC, collivier commented
@gkunz I think this pr can be safely closed. ok?

2022-05-08 10:23 UTC, gkunz commented
Closing since we moved to a new version of Sphinx after converting all md files.

2022-05-08 10:23 UTC, closed without merging