[RA]: Fix Reference Architecture link in star tpage
cntt-n/CNTT pull request #2962
Opened 2022-05-09 08:02 UTC by CsatariGergely

2022-05-09 15:37 UTC, karinesevilla commented on doc/index.rst
> +    Reference Architectures </ref_arch/README>
+1

2022-05-12 15:28 UTC, CsatariGergely commented
> Sorry but I don't understand your point here. If we consider sphinx, it should be index.rst. There is a falsy link to README to please github user (ideally we should have renamed README.rst index.rst). but all-in-all we will fully README like the bundly history in GSMA...

@collivier at the moment there is no index.rst. I will create a symlink to README.md and use that.

2022-05-16 14:10 UTC, pgoyal01 approved these changes

2022-05-16 14:38 UTC, ildikov approved these changes

2022-05-16 15:22 UTC, collivier requested changes
@CsatariGergely I don't get your point. The issue is more on the caller side.
We don't need a specific index.rst as there is no specific sphinx project. We could rename all README index but it will diverge from default Github rendering 

We could gate ra top dir as rc top dir but I would ask for tox.ini test-requirements, etc.

2022-05-16 15:23 UTC, collivier commented
@CsatariGergely yes the issue is more on https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/README.rst

2022-05-17 11:13 UTC, rgstori approved these changes

2022-05-18 13:41 UTC, CsatariGergely commented
Sphinx requires an index.rst while GitHub assumes a README.md . I copied this solution with linking from RI or RC (I do not remember anymore) in the hope that it will work for RA-s too. 
Can you @collivier explain what solution you expect to get this merged? At the moment RA2 is not accessible in readthedocs due to this bug, so this would need a quicker fix. 
Thanks.

2022-05-19 15:24 UTC, CsatariGergely commented
@collivier can you please check my comment. We really need to have a resolution for this. 
@scottsteinbrueck please review. 

Thanks.

2022-05-22 12:41 UTC, gkunz commented
@CsatariGergely shouldn't it be the other way around: have all the real content in index.rst and then a link to a README to allow rendering on GitHub. This would also be consistent with RC1/2 and (somewhat) with RI1/2.

2022-05-23 06:47 UTC, CsatariGergely commented
> @CsatariGergely shouldn't it be the other way around: have all the real content in index.rst and then a link to a README to allow rendering on GitHub. This would also be consistent with RC1/2 and (somewhat) with RI1/2.

Okey, let's try that. Done in [000672e](https://github.com/cntt-n/CNTT/pull/2962/commits/000672ef73e60278820bb9cc28baa54592d195a6)

2022-05-23 12:16 UTC, walterkozlowski approved these changes

2022-05-23 16:18 UTC, collivier commented
> Can you @collivier explain what solution you expect to get this merged? At the moment RA2 is not accessible in readthedocs due to this bug, so this would need a quicker fix.

> @collivier can you please check my comment. We really need to have a resolution for this.

The previous solution implemented in RCX and in RA1 seems good. If you consider sphinx as first choice, README.rst should be a link to index.rst. In RA1 it was the opposite firstly focusing priorly on backward compatibility.

About the overall thread: the main problem here is why the main doc isn't gated as such and why we allow the doc to be merged and published with incorrect labels or document unused.

You can spam me to merge but I would never agree to merge a an RST file named MD. I could have allowed on the suffix .txt  - Github render index.rst too...

2022-05-29 11:57 UTC, walterkozlowski commented
@collivier, can you please check and approve if it is ok for merge, thanks

2022-05-30 13:56 UTC, collivier approved these changes

2022-05-30 13:56 UTC, merged