[ra2 ch4] fix ch4 build errors
cntt-n/CNTT pull request #3022
Opened 2022-06-06 15:42 UTC by rgstori

2022-06-06 16:18 UTC, pgoyal01 reviewed
Table 4-6 doesn't render: misaligned columns in line 513

2022-06-06 17:51 UTC, rgstori commented
> @rgstori Table 4-6 doesn't render: misaligned columns in line 513

thanks! fixed now

2022-06-07 11:28 UTC, collivier requested changes
./chapters/chapter04.rst:446: D000 Malformed table.
./chapters/chapter04.rst:992: D000 Inline interpreted text or phrase reference start-string without end-string.

\+ https://github.com/cntt-n/CNTT/issues/3031

2022-06-07 11:30 UTC, collivier approved these changes

2022-06-07 11:31 UTC, merged