[RM Ch05] Corrections from GSMA review
cntt-n/CNTT pull request #3168
Opened 2022-09-09 14:27 UTC by walterkozlowski

2022-09-09 14:39 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter05.rst
> +| infra.hw.cpu.cfg.004 | Simultaneous Multithreading     | SMT enabled that allows each    | Y           |Optional     |
SMT, even for High Performance (HP), is usually "Y" -- there are very few HP exceptions where you have the second thread disabled (SMT disabled).

High Performance does require that both threads are allocated to the same workload compute resource, not different workloads.

2022-09-09 14:39 UTC, pgoyal01 approved these changes

2022-09-09 14:50 UTC, collivier requested changes
lgtm but they lots of RST issues to fix
https://build.opnfv.org/ci/job/cntt-tox-rm/1749/console

```
./chapters/chapter06.rst:62: D000 Unexpected indentation.
./chapters/chapter06.rst:187: D000 Malformed table.
./chapters/chapter04.rst:267: D000 Malformed table.
./chapters/chapter04.rst:614: D000 Malformed table.
./chapters/chapter04.rst:662: D000 Malformed table.
./chapters/chapter08.rst:386: D000 Inline interpreted text or phrase reference start-string without end-string.
./chapters/chapter08.rst:396: D000 Malformed table.
./chapters/chapter09.rst:386: D000 Malformed table.
./chapters/chapter05.rst:263: D000 Malformed table.
./chapters/chapter03.rst:1243: D000 Malformed table.
./chapters/chapter03.rst:1282: D000 Malformed table.
```

2022-09-12 07:08 UTC, collivier commented
@walterkozlowski do u need help to fix this issues?

2022-09-12 12:02 UTC, walterkozlowski commented
@collivier, yes please.  Thank you for your offer!

2022-09-12 13:10 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter05.rst
> +| infra.net.cfg.001 | Connection Point     |IO virtualisation|  eg. virtio1.1                           |              |
```suggestion
| infra.net.cfg.001 | Connection Point     |IO virtualisation|  e.g., virtio1.1                         |              |
```

2022-09-12 13:11 UTC, pgoyal01 commented on doc/ref_model/chapters/chapter05.rst
> +| infra.hw.cpu.cfg.004 | Simultaneous Multithreading     | SMT enabled that allows each    | Y           | Y    |
The right boundary marker needs to be aligned

2022-09-12 18:26 UTC, collivier approved these changes
I approved but I think Pankaj's proposal should be committed.

2022-09-13 05:14 UTC, walterkozlowski commented
Changed proposed by @pgoyal01 done.

2022-09-13 05:40 UTC, pgoyal01 approved these changes

2022-09-13 13:51 UTC, ildikov approved these changes

2022-09-14 15:33 UTC, karinesevilla approved these changes

2022-09-14 15:34 UTC, merged