[ra2] clarify gen.cnt.04
cntt-n/CNTT pull request #3216
Opened 2022-10-06 13:24 UTC by rgstori

fixes #2551

2022-10-13 15:10 UTC, CsatariGergely requested changes

2022-10-13 15:10 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter02.rst
> +     - The Architecture must support clearly defined abstraction layers - from hardware
```suggestion
     - The Architecture must support clearly defined abstraction layers - from hardware
```

2022-10-13 15:12 UTC, CsatariGergely approved these changes

2022-10-14 07:07 UTC, ulikleber approved these changes

2022-10-14 14:21 UTC, pgoyal01 requested changes

2022-10-14 14:21 UTC, pgoyal01 commented on doc/ref_arch/kubernetes/chapters/chapter02.rst
> +       infrastructure (supporting the platform) to cloud platform (main concern of this
it doesn't have to be "cloud" platform; "containerisation" can be deleted
```suggestion
       infrastructure (supporting the platform) to the containerisation platform (the main concern of this
```

2022-10-14 14:21 UTC, pgoyal01 commented on doc/ref_arch/kubernetes/chapters/chapter02.rst
> +       Architecture) to application (workloads running on the platform).
```suggestion
       Architecture) to the applications (workloads running on the platform).
```

2022-11-10 17:29 UTC, pgoyal01 approved these changes

2022-11-10 17:29 UTC, merged