[ra2ch7]: Removing DANM reference and adding reference to the multi networking effort
cntt-n/CNTT pull request #3227
Opened 2022-11-08 08:55 UTC by CsatariGergely

2022-11-10 15:16 UTC, rgstori approved these changes

2022-11-10 17:26 UTC, pgoyal01 requested changes

2022-11-11 12:49 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +   created to support multiple Pod interfaces natively. The group working on the KEP have `regular meetings
I've removed the meeting info in [1b42b8a](https://github.com/cntt-n/CNTT/pull/3227/commits/1b42b8af6cea31c1319f283f9deb6356156fbaed). 
@pgoyal01 : What do you mean on first use needs to be defined?

2022-11-11 17:19 UTC, pgoyal01 commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +   created to support multiple Pod interfaces natively. The group working on the KEP have `regular meetings
@CsatariGergely KEP is being used for the first time and as such the acronym needs to be defined.

2022-11-17 19:39 UTC, petorre approved these changes

2022-11-18 14:43 UTC, CsatariGergely commented on doc/ref_arch/kubernetes/chapters/chapter07.rst
> +   created to support multiple Pod interfaces natively. The group working on the KEP have `regular meetings
Fixed in [768ce66](https://github.com/cntt-n/CNTT/pull/3227/commits/768ce661088706ec8f63fce52296f4b8fc57ca4e)

2022-11-25 15:09 UTC, tomkivlin approved these changes

2022-11-29 09:34 UTC, merged